version: 0.2

phases:
  install:
    commands:
      - |
          amazon-linux-extras install php7.2 -y
          yum install -y php-mbstring php-xml php-bcmath

          curl -sS https://getcomposer.org/installer | php
          cp composer.phar /usr/local/bin/composer
          ln -s /usr/local/bin/composer /usr/bin/composer

          yum install -y git
          yum install -y zip unzip
    finally:
      - echo "install > finally"
  pre_build:
    commands:
      - echo "pre_build > commands"
    finally:
      - echo "pre_build > finally"
  build:
    commands:
      - rm -rf .git .gitignore README.md
      - composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader
    finally:
      - echo "build > finally"
  post_build:
    commands:
      - echo "post_build > commands"
    finally:
      - echo "post_build > finally"
artifacts:
  files:
    - '**/*'
